(foreign-declare "
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
//#include <libavdevice/avdevice.h>
//#include <libavutil/time.h>
")

(include "foreign-enum.scm")

(include "enum-codecs.scm")

(define pixfmts
  (foreign-enum
   (none                "AV_PIX_FMT_NONE"            "")
   (yuv420p             "AV_PIX_FMT_YUV420P"         "planar YUV 4:2:0, 12bpp, (1 Cr & Cb sample per 2x2 Y samples)")
   (yuyv422             "AV_PIX_FMT_YUYV422"         "packed YUV 4:2:2, 16bpp, Y0 Cb Y1 Cr")
   (rgb24               "AV_PIX_FMT_RGB24"           "packed RGB 8:8:8, 24bpp, RGBRGB...")
   (bgr24               "AV_PIX_FMT_BGR24"           "packed RGB 8:8:8, 24bpp, BGRBGR...")
   (yuv422p             "AV_PIX_FMT_YUV422P"         "planar YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)")
   (yuv444p             "AV_PIX_FMT_YUV444P"         "planar YUV 4:4:4, 24bpp, (1 Cr & Cb sample per 1x1 Y samples)")
   (yuv410p             "AV_PIX_FMT_YUV410P"         "planar YUV 4:1:0,  9bpp, (1 Cr & Cb sample per 4x4 Y samples)")
   (yuv411p             "AV_PIX_FMT_YUV411P"         "planar YUV 4:1:1, 12bpp, (1 Cr & Cb sample per 4x1 Y samples)")
   (gray8               "AV_PIX_FMT_GRAY8"           "Y        ,  8bpp")
   (monowhite           "AV_PIX_FMT_MONOWHITE"       "Y        ,  1bpp, 0 is white, 1 is black, in each byte pixels are ordered from the msb to the lsb")
   (monoblack           "AV_PIX_FMT_MONOBLACK"       "Y        ,  1bpp, 0 is black, 1 is white, in each byte pixels are ordered from the msb to the lsb")
   (pal8                "AV_PIX_FMT_PAL8"            "8 bits with AV_PIX_FMT_RGB32 palette")
   (yuvj420p            "AV_PIX_FMT_YUVJ420P"        "planar YUV 4:2:0, 12bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV420P and setting color_range")
   (yuvj422p            "AV_PIX_FMT_YUVJ422P"        "planar YUV 4:2:2, 16bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV422P and setting color_range")
   (yuvj444p            "AV_PIX_FMT_YUVJ444P"        "planar YUV 4:4:4, 24bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV444P and setting color_range")
   (xvmc-mpeg2-mc       "AV_PIX_FMT_XVMC_MPEG2_MC"   "FF_API_XVMC" "XVideo Motion Acceleration via common packet passing")
   (xvmc-mpeg2-idct     "AV_PIX_FMT_XVMC_MPEG2_IDCT" "FF_API_XVMC" "")
   (xvmc                "AV_PIX_FMT_XVMC"            "")
   (uyvy422             "AV_PIX_FMT_UYVY422"         "packed YUV 4:2:2, 16bpp, Cb Y0 Cr Y1")
   (uyyvyy411           "AV_PIX_FMT_UYYVYY411"       "packed YUV 4:1:1, 12bpp, Cb Y0 Y1 Cr Y2 Y3")
   (bgr8                "AV_PIX_FMT_BGR8"            "packed RGB 3:3:2,  8bpp, (msb)2B 3G 3R(lsb)")
   (bgr4                "AV_PIX_FMT_BGR4"            "packed RGB 1:2:1 bitstream,  4bpp, (msb)1B 2G 1R(lsb), a byte contains two pixels, the first pixel in the byte is the one composed by the 4 msb bits")
   (bgr4-byte           "AV_PIX_FMT_BGR4_BYTE"       "packed RGB 1:2:1,  8bpp, (msb)1B 2G 1R(lsb)")
   (rgb8                "AV_PIX_FMT_RGB8"            "packed RGB 3:3:2,  8bpp, (msb)2R 3G 3B(lsb)")
   (rgb4                "AV_PIX_FMT_RGB4"            "packed RGB 1:2:1 bitstream,  4bpp, (msb)1R 2G 1B(lsb), a byte contains two pixels, the first pixel in the byte is the one composed by the 4 msb bits")
   (rgb4-byte           "AV_PIX_FMT_RGB4_BYTE"       "packed RGB 1:2:1,  8bpp, (msb)1R 2G 1B(lsb)")
   (nv12                "AV_PIX_FMT_NV12"            "planar YUV 4:2:0, 12bpp, 1 plane for Y and 1 plane for the UV components, which are interleaved (first byte U and the following byte V)")
   (nv21                "AV_PIX_FMT_NV21"            "as above, but U and V bytes are swapped")
   (argb                "AV_PIX_FMT_ARGB"            "packed ARGB 8:8:8:8, 32bpp, ARGBARGB...")
   (rgba                "AV_PIX_FMT_RGBA"            "packed RGBA 8:8:8:8, 32bpp, RGBARGBA...")
   (abgr                "AV_PIX_FMT_ABGR"            "packed ABGR 8:8:8:8, 32bpp, ABGRABGR...")
   (bgra                "AV_PIX_FMT_BGRA"            "packed BGRA 8:8:8:8, 32bpp, BGRABGRA...")
   (gray16be            "AV_PIX_FMT_GRAY16BE"        "Y        , 16bpp, big-endian")
   (gray16le            "AV_PIX_FMT_GRAY16LE"        "Y        , 16bpp, little-endian")
   (yuv440p             "AV_PIX_FMT_YUV440P"         "planar YUV 4:4:0 (1 Cr & Cb sample per 1x2 Y samples)")
   (yuvj440p            "AV_PIX_FMT_YUVJ440P"        "planar YUV 4:4:0 full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV440P and setting color_range")
   (yuva420p            "AV_PIX_FMT_YUVA420P"        "planar YUV 4:2:0, 20bpp, (1 Cr & Cb sample per 2x2 Y & A samples)")
   (vdpau-h264          "AV_PIX_FMT_VDPAU_H264"   "FF_API_VDPAU"   "H.264 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (vdpau-mpeg1         "AV_PIX_FMT_VDPAU_MPEG1"  "FF_API_VDPAU"   "MPEG-1 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (vdpau-mpeg2         "AV_PIX_FMT_VDPAU_MPEG2"  "FF_API_VDPAU"   "MPEG-2 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (vdpau-wmv3          "AV_PIX_FMT_VDPAU_WMV3"   "FF_API_VDPAU"   "WMV3 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (vdpau-vc1           "AV_PIX_FMT_VDPAU_VC1"    "FF_API_VDPAU"   "VC-1 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (rgb48be             "AV_PIX_FMT_RGB48BE"         "packed RGB 16:16:16, 48bpp, 16R, 16G, 16B, the 2-byte value for each R/G/B component is stored as big-endian")
   (rgb48le             "AV_PIX_FMT_RGB48LE"         "packed RGB 16:16:16, 48bpp, 16R, 16G, 16B, the 2-byte value for each R/G/B component is stored as little-endian")
   (rgb565be            "AV_PIX_FMT_RGB565BE"        "packed RGB 5:6:5, 16bpp, (msb)   5R 6G 5B(lsb), big-endian")
   (rgb565le            "AV_PIX_FMT_RGB565LE"        "packed RGB 5:6:5, 16bpp, (msb)   5R 6G 5B(lsb), little-endian")
   (rgb555be            "AV_PIX_FMT_RGB555BE"        "packed RGB 5:5:5, 16bpp, (msb)1X 5R 5G 5B(lsb), big-endian   , X=unused/undefined")
   (rgb555le            "AV_PIX_FMT_RGB555LE"        "packed RGB 5:5:5, 16bpp, (msb)1X 5R 5G 5B(lsb), little-endian, X=unused/undefined")
   (bgr565be            "AV_PIX_FMT_BGR565BE"        "packed BGR 5:6:5, 16bpp, (msb)   5B 6G 5R(lsb), big-endian")
   (bgr565le            "AV_PIX_FMT_BGR565LE"        "packed BGR 5:6:5, 16bpp, (msb)   5B 6G 5R(lsb), little-endian")
   (bgr555be            "AV_PIX_FMT_BGR555BE"        "packed BGR 5:5:5, 16bpp, (msb)1X 5B 5G 5R(lsb), big-endian   , X=unused/undefined")
   (bgr555le            "AV_PIX_FMT_BGR555LE"        "packed BGR 5:5:5, 16bpp, (msb)1X 5B 5G 5R(lsb), little-endian, X=unused/undefined")
   (vaapi-moco          "AV_PIX_FMT_VAAPI_MOCO"   "FF_API_VAAPI"   "HW acceleration through VA API at motion compensation entry-point, Picture.data[3] contains a vaapi_render_state struct which contains macroblocks as well as various fields extracted from headers")
   (vaapi-idct          "AV_PIX_FMT_VAAPI_IDCT"   "FF_API_VAAPI"   "HW acceleration through VA API at IDCT entry-point, Picture.data[3] contains a vaapi_render_state struct which contains fields extracted from headers")
   (vaapi-vld           "AV_PIX_FMT_VAAPI_VLD"    "FF_API_VAAPI"   "HW decoding through VA API, Picture.data[3] contains a VASurfaceID")
   (vaapi               "AV_PIX_FMT_VAAPI"           "Hardware acceleration through VA-API, data[3] contains a VASurfaceID.")
   (yuv420p16le         "AV_PIX_FMT_YUV420P16LE"     "planar YUV 4:2:0, 24bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian")
   (yuv420p16be         "AV_PIX_FMT_YUV420P16BE"     "planar YUV 4:2:0, 24bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian")
   (yuv422p16le         "AV_PIX_FMT_YUV422P16LE"     "planar YUV 4:2:2, 32bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (yuv422p16be         "AV_PIX_FMT_YUV422P16BE"     "planar YUV 4:2:2, 32bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (yuv444p16le         "AV_PIX_FMT_YUV444P16LE"     "planar YUV 4:4:4, 48bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian")
   (yuv444p16be         "AV_PIX_FMT_YUV444P16BE"     "planar YUV 4:4:4, 48bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian")
   (vdpau-mpeg4         "AV_PIX_FMT_VDPAU_MPEG4"  "FF_API_VDPAU"     "MPEG-4 HW decoding with VDPAU, data[0] contains a vdpau_render_state struct which contains the bitstream of the slices as well as various fields extracted from headers")
   (dxva2-vld           "AV_PIX_FMT_DXVA2_VLD"       "HW decoding through DXVA2, Picture.data[3] contains a LPDIRECT3DSURFACE9 pointer")
   (rgb444le            "AV_PIX_FMT_RGB444LE"        "packed RGB 4:4:4, 16bpp, (msb)4X 4R 4G 4B(lsb), little-endian, X=unused/undefined")
   (rgb444be            "AV_PIX_FMT_RGB444BE"        "packed RGB 4:4:4, 16bpp, (msb)4X 4R 4G 4B(lsb), big-endian,    X=unused/undefined")
   (bgr444le            "AV_PIX_FMT_BGR444LE"        "packed BGR 4:4:4, 16bpp, (msb)4X 4B 4G 4R(lsb), little-endian, X=unused/undefined")
   (bgr444be            "AV_PIX_FMT_BGR444BE"        "packed BGR 4:4:4, 16bpp, (msb)4X 4B 4G 4R(lsb), big-endian,    X=unused/undefined")
   (ya8                 "AV_PIX_FMT_YA8"             "8 bits gray, 8 bits alpha")
   (y400a               "AV_PIX_FMT_Y400A"           "alias for AV_PIX_FMT_YA8")
   (gray8a              "AV_PIX_FMT_GRAY8A"          "alias for AV_PIX_FMT_YA8")
   (bgr48be             "AV_PIX_FMT_BGR48BE"         "packed RGB 16:16:16, 48bpp, 16B, 16G, 16R, the 2-byte value for each R/G/B component is stored as big-endian")
   (bgr48le             "AV_PIX_FMT_BGR48LE"         "packed RGB 16:16:16, 48bpp, 16B, 16G, 16R, the 2-byte value for each R/G/B component is stored as little-endian")
   (yuv420p9be          "AV_PIX_FMT_YUV420P9BE"      "planar YUV 4:2:0, 13.5bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian")
   (yuv420p9le          "AV_PIX_FMT_YUV420P9LE"      "planar YUV 4:2:0, 13.5bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian")
   (yuv420p10be         "AV_PIX_FMT_YUV420P10BE"     "planar YUV 4:2:0, 15bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian")
   (yuv420p10le         "AV_PIX_FMT_YUV420P10LE"     "planar YUV 4:2:0, 15bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian")
   (yuv422p10be         "AV_PIX_FMT_YUV422P10BE"     "planar YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (yuv422p10le         "AV_PIX_FMT_YUV422P10LE"     "planar YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (yuv444p9be          "AV_PIX_FMT_YUV444P9BE"      "planar YUV 4:4:4, 27bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian")
   (yuv444p9le          "AV_PIX_FMT_YUV444P9LE"      "planar YUV 4:4:4, 27bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian")
   (yuv444p10be         "AV_PIX_FMT_YUV444P10BE"     "planar YUV 4:4:4, 30bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian")
   (yuv444p10le         "AV_PIX_FMT_YUV444P10LE"     "planar YUV 4:4:4, 30bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian")
   (yuv422p9be          "AV_PIX_FMT_YUV422P9BE"      "planar YUV 4:2:2, 18bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (yuv422p9le          "AV_PIX_FMT_YUV422P9LE"      "planar YUV 4:2:2, 18bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (vda-vld             "AV_PIX_FMT_VDA_VLD"         "hardware decoding through VDA")
   (gbrp                "AV_PIX_FMT_GBRP"            "planar GBR 4:4:4 24bpp")
   (gbr24p              "AV_PIX_FMT_GBR24P"          "alias for #AV_PIX_FMT_GBRP")
   (gbrp9be             "AV_PIX_FMT_GBRP9BE"         "planar GBR 4:4:4 27bpp, big-endian")
   (gbrp9le             "AV_PIX_FMT_GBRP9LE"         "planar GBR 4:4:4 27bpp, little-endian")
   (gbrp10be            "AV_PIX_FMT_GBRP10BE"        "planar GBR 4:4:4 30bpp, big-endian")
   (gbrp10le            "AV_PIX_FMT_GBRP10LE"        "planar GBR 4:4:4 30bpp, little-endian")
   (gbrp16be            "AV_PIX_FMT_GBRP16BE"        "planar GBR 4:4:4 48bpp, big-endian")
   (gbrp16le            "AV_PIX_FMT_GBRP16LE"        "planar GBR 4:4:4 48bpp, little-endian")
   (yuva422p            "AV_PIX_FMT_YUVA422P"        "planar YUV 4:2:2 24bpp, (1 Cr & Cb sample per 2x1 Y & A samples)")
   (yuva444p            "AV_PIX_FMT_YUVA444P"        "planar YUV 4:4:4 32bpp, (1 Cr & Cb sample per 1x1 Y & A samples)")
   (yuva420p9be         "AV_PIX_FMT_YUVA420P9BE"     "planar YUV 4:2:0 22.5bpp, (1 Cr & Cb sample per 2x2 Y & A samples), big-endian")
   (yuva420p9le         "AV_PIX_FMT_YUVA420P9LE"     "planar YUV 4:2:0 22.5bpp, (1 Cr & Cb sample per 2x2 Y & A samples), little-endian")
   (yuva422p9be         "AV_PIX_FMT_YUVA422P9BE"     "planar YUV 4:2:2 27bpp, (1 Cr & Cb sample per 2x1 Y & A samples), big-endian")
   (yuva422p9le         "AV_PIX_FMT_YUVA422P9LE"     "planar YUV 4:2:2 27bpp, (1 Cr & Cb sample per 2x1 Y & A samples), little-endian")
   (yuva444p9be         "AV_PIX_FMT_YUVA444P9BE"     "planar YUV 4:4:4 36bpp, (1 Cr & Cb sample per 1x1 Y & A samples), big-endian")
   (yuva444p9le         "AV_PIX_FMT_YUVA444P9LE"     "planar YUV 4:4:4 36bpp, (1 Cr & Cb sample per 1x1 Y & A samples), little-endian")
   (yuva420p10be        "AV_PIX_FMT_YUVA420P10BE"    "planar YUV 4:2:0 25bpp, (1 Cr & Cb sample per 2x2 Y & A samples, big-endian)")
   (yuva420p10le        "AV_PIX_FMT_YUVA420P10LE"    "planar YUV 4:2:0 25bpp, (1 Cr & Cb sample per 2x2 Y & A samples, little-endian)")
   (yuva422p10be        "AV_PIX_FMT_YUVA422P10BE"    "planar YUV 4:2:2 30bpp, (1 Cr & Cb sample per 2x1 Y & A samples, big-endian)")
   (yuva422p10le        "AV_PIX_FMT_YUVA422P10LE"    "planar YUV 4:2:2 30bpp, (1 Cr & Cb sample per 2x1 Y & A samples, little-endian)")
   (yuva444p10be        "AV_PIX_FMT_YUVA444P10BE"    "planar YUV 4:4:4 40bpp, (1 Cr & Cb sample per 1x1 Y & A samples, big-endian)")
   (yuva444p10le        "AV_PIX_FMT_YUVA444P10LE"    "planar YUV 4:4:4 40bpp, (1 Cr & Cb sample per 1x1 Y & A samples, little-endian)")
   (yuva420p16be        "AV_PIX_FMT_YUVA420P16BE"    "planar YUV 4:2:0 40bpp, (1 Cr & Cb sample per 2x2 Y & A samples, big-endian)")
   (yuva420p16le        "AV_PIX_FMT_YUVA420P16LE"    "planar YUV 4:2:0 40bpp, (1 Cr & Cb sample per 2x2 Y & A samples, little-endian)")
   (yuva422p16be        "AV_PIX_FMT_YUVA422P16BE"    "planar YUV 4:2:2 48bpp, (1 Cr & Cb sample per 2x1 Y & A samples, big-endian)")
   (yuva422p16le        "AV_PIX_FMT_YUVA422P16LE"    "planar YUV 4:2:2 48bpp, (1 Cr & Cb sample per 2x1 Y & A samples, little-endian)")
   (yuva444p16be        "AV_PIX_FMT_YUVA444P16BE"    "planar YUV 4:4:4 64bpp, (1 Cr & Cb sample per 1x1 Y & A samples, big-endian)")
   (yuva444p16le        "AV_PIX_FMT_YUVA444P16LE"    "planar YUV 4:4:4 64bpp, (1 Cr & Cb sample per 1x1 Y & A samples, little-endian)")
   (vdpau               "AV_PIX_FMT_VDPAU"           "HW acceleration through VDPAU, Picture.data[3] contains a VdpVideoSurface")
   (xyz12le             "AV_PIX_FMT_XYZ12LE"         "packed XYZ 4:4:4, 36 bpp, (msb) 12X, 12Y, 12Z (lsb), the 2-byte value for each X/Y/Z is stored as little-endian, the 4 lower bits are set to 0")
   (xyz12be             "AV_PIX_FMT_XYZ12BE"         "packed XYZ 4:4:4, 36 bpp, (msb) 12X, 12Y, 12Z (lsb), the 2-byte value for each X/Y/Z is stored as big-endian, the 4 lower bits are set to 0")
   (nv16                "AV_PIX_FMT_NV16"            "interleaved chroma YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)")
   (nv20le              "AV_PIX_FMT_NV20LE"          "interleaved chroma YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (nv20be              "AV_PIX_FMT_NV20BE"          "interleaved chroma YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (rgba64be            "AV_PIX_FMT_RGBA64BE"        "packed RGBA 16:16:16:16, 64bpp, 16R, 16G, 16B, 16A, the 2-byte value for each R/G/B/A component is stored as big-endian")
   (rgba64le            "AV_PIX_FMT_RGBA64LE"        "packed RGBA 16:16:16:16, 64bpp, 16R, 16G, 16B, 16A, the 2-byte value for each R/G/B/A component is stored as little-endian")
   (bgra64be            "AV_PIX_FMT_BGRA64BE"        "packed RGBA 16:16:16:16, 64bpp, 16B, 16G, 16R, 16A, the 2-byte value for each R/G/B/A component is stored as big-endian")
   (bgra64le            "AV_PIX_FMT_BGRA64LE"        "packed RGBA 16:16:16:16, 64bpp, 16B, 16G, 16R, 16A, the 2-byte value for each R/G/B/A component is stored as little-endian")
   (yvyu422             "AV_PIX_FMT_YVYU422"         "packed YUV 4:2:2, 16bpp, Y0 Cr Y1 Cb")
   (vda                 "AV_PIX_FMT_VDA"             "HW acceleration through VDA, data[3] contains a CVPixelBufferRef")
   (ya16be              "AV_PIX_FMT_YA16BE"          "16 bits gray, 16 bits alpha (big-endian)")
   (ya16le              "AV_PIX_FMT_YA16LE"          "16 bits gray, 16 bits alpha (little-endian)")
   (gbrap               "AV_PIX_FMT_GBRAP"           "planar GBRA 4:4:4:4 32bpp")
   (gbrap16be           "AV_PIX_FMT_GBRAP16BE"       "planar GBRA 4:4:4:4 64bpp, big-endian")
   (gbrap16le           "AV_PIX_FMT_GBRAP16LE"       "planar GBRA 4:4:4:4 64bpp, little-endian")
   (qsv                 "AV_PIX_FMT_QSV"             "HW acceleration through QSV, data[3] contains a pointer to the mfxFrameSurface1 structure")
   (mmal                "AV_PIX_FMT_MMAL"            "HW acceleration though MMAL, data[3] contains a pointer to the MMAL_BUFFER_HEADER_T structure")
   (d3d11va-vld         "AV_PIX_FMT_D3D11VA_VLD"     "HW decoding through Direct3D11 via old API, Picture.data[3] contains a ID3D11VideoDecoderOutputView pointer")
   (cuda                "AV_PIX_FMT_CUDA"            "HW acceleration through CUDA. data[i] contain CUdeviceptr pointers exactly as for system memory frames")
   (0rgb                "AV_PIX_FMT_0RGB"            "packed RGB 8:8:8, 32bpp, XRGBXRGB...   X=unused/undefined")
   (rgb0                "AV_PIX_FMT_RGB0"            "packed RGB 8:8:8, 32bpp, RGBXRGBX...   X=unused/undefined")
   (0bgr                "AV_PIX_FMT_0BGR"            "packed BGR 8:8:8, 32bpp, XBGRXBGR...   X=unused/undefined")
   (bgr0                "AV_PIX_FMT_BGR0"            "packed BGR 8:8:8, 32bpp, BGRXBGRX...   X=unused/undefined")
   (yuv420p12be         "AV_PIX_FMT_YUV420P12BE"     "planar YUV 4:2:0,18bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian")
   (yuv420p12le         "AV_PIX_FMT_YUV420P12LE"     "planar YUV 4:2:0,18bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian")
   (yuv420p14be         "AV_PIX_FMT_YUV420P14BE"     "planar YUV 4:2:0,21bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian")
   (yuv420p14le         "AV_PIX_FMT_YUV420P14LE"     "planar YUV 4:2:0,21bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian")
   (yuv422p12be         "AV_PIX_FMT_YUV422P12BE"     "planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (yuv422p12le         "AV_PIX_FMT_YUV422P12LE"     "planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (yuv422p14be         "AV_PIX_FMT_YUV422P14BE"     "planar YUV 4:2:2,28bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian")
   (yuv422p14le         "AV_PIX_FMT_YUV422P14LE"     "planar YUV 4:2:2,28bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian")
   (yuv444p12be         "AV_PIX_FMT_YUV444P12BE"     "planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian")
   (yuv444p12le         "AV_PIX_FMT_YUV444P12LE"     "planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian")
   (yuv444p14be         "AV_PIX_FMT_YUV444P14BE"     "planar YUV 4:4:4,42bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian")
   (yuv444p14le         "AV_PIX_FMT_YUV444P14LE"     "planar YUV 4:4:4,42bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian")
   (gbrp12be            "AV_PIX_FMT_GBRP12BE"        "planar GBR 4:4:4 36bpp, big-endian")
   (gbrp12le            "AV_PIX_FMT_GBRP12LE"        "planar GBR 4:4:4 36bpp, little-endian")
   (gbrp14be            "AV_PIX_FMT_GBRP14BE"        "planar GBR 4:4:4 42bpp, big-endian")
   (gbrp14le            "AV_PIX_FMT_GBRP14LE"        "planar GBR 4:4:4 42bpp, little-endian")
   (yuvj411p            "AV_PIX_FMT_YUVJ411P"        "planar YUV 4:1:1, 12bpp, (1 Cr & Cb sample per 4x1 Y samples) full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV411P and setting color_range")
   (bayer-bggr8         "AV_PIX_FMT_BAYER_BGGR8"     "bayer, BGBG..(odd line), GRGR..(even line), 8-bit samples */")
   (bayer-rggb8         "AV_PIX_FMT_BAYER_RGGB8"     "bayer, RGRG..(odd line), GBGB..(even line), 8-bit samples */")
   (bayer-gbrg8         "AV_PIX_FMT_BAYER_GBRG8"     "bayer, GBGB..(odd line), RGRG..(even line), 8-bit samples */")
   (bayer-grbg8         "AV_PIX_FMT_BAYER_GRBG8"     "bayer, GRGR..(odd line), BGBG..(even line), 8-bit samples */")
   (bayer-bggr16le      "AV_PIX_FMT_BAYER_BGGR16LE"  "bayer, BGBG..(odd line), GRGR..(even line), 16-bit samples, little-endian */")
   (bayer-bggr16be      "AV_PIX_FMT_BAYER_BGGR16BE"  "bayer, BGBG..(odd line), GRGR..(even line), 16-bit samples, big-endian */")
   (bayer-rggb16le      "AV_PIX_FMT_BAYER_RGGB16LE"  "bayer, RGRG..(odd line), GBGB..(even line), 16-bit samples, little-endian */")
   (bayer-rggb16be      "AV_PIX_FMT_BAYER_RGGB16BE"  "bayer, RGRG..(odd line), GBGB..(even line), 16-bit samples, big-endian */")
   (bayer-gbrg16le      "AV_PIX_FMT_BAYER_GBRG16LE"  "bayer, GBGB..(odd line), RGRG..(even line), 16-bit samples, little-endian */")
   (bayer-gbrg16be      "AV_PIX_FMT_BAYER_GBRG16BE"  "bayer, GBGB..(odd line), RGRG..(even line), 16-bit samples, big-endian */")
   (bayer-grbg16le      "AV_PIX_FMT_BAYER_GRBG16LE"  "bayer, GRGR..(odd line), BGBG..(even line), 16-bit samples, little-endian */")
   (bayer-grbg16be      "AV_PIX_FMT_BAYER_GRBG16BE"  "bayer, GRGR..(odd line), BGBG..(even line), 16-bit samples, big-endian */")
   (yuv440p10le         "AV_PIX_FMT_YUV440P10LE"     "planar YUV 4:4:0,20bpp, (1 Cr & Cb sample per 1x2 Y samples), little-endian")
   (yuv440p10be         "AV_PIX_FMT_YUV440P10BE"     "planar YUV 4:4:0,20bpp, (1 Cr & Cb sample per 1x2 Y samples), big-endian")
   (yuv440p12le         "AV_PIX_FMT_YUV440P12LE"     "planar YUV 4:4:0,24bpp, (1 Cr & Cb sample per 1x2 Y samples), little-endian")
   (yuv440p12be         "AV_PIX_FMT_YUV440P12BE"     "planar YUV 4:4:0,24bpp, (1 Cr & Cb sample per 1x2 Y samples), big-endian")
   (ayuv64le            "AV_PIX_FMT_AYUV64LE"        "packed AYUV 4:4:4,64bpp (1 Cr & Cb sample per 1x1 Y & A samples), little-endian")
   (ayuv64be            "AV_PIX_FMT_AYUV64BE"        "packed AYUV 4:4:4,64bpp (1 Cr & Cb sample per 1x1 Y & A samples), big-endian")
   (videotoolbox        "AV_PIX_FMT_VIDEOTOOLBOX"    "hardware decoding through Videotoolbox")
   (p010le              "AV_PIX_FMT_P010LE"          "like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian")
   (p010be              "AV_PIX_FMT_P010BE"          "like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian")
   (gbrap12be           "AV_PIX_FMT_GBRAP12BE"       "planar GBR 4:4:4:4 48bpp, big-endian")
   (gbrap12le           "AV_PIX_FMT_GBRAP12LE"       "planar GBR 4:4:4:4 48bpp, little-endian")
   (gbrap10be           "AV_PIX_FMT_GBRAP10BE"       "planar GBR 4:4:4:4 40bpp, big-endian")
   (gbrap10le           "AV_PIX_FMT_GBRAP10LE"       "planar GBR 4:4:4:4 40bpp, little-endian")
   (mediacodec          "AV_PIX_FMT_MEDIACODEC"      "hardware decoding through MediaCodec")
   (gray12be            "AV_PIX_FMT_GRAY12BE"        "Y        , 12bpp, big-endian")
   (gray12le            "AV_PIX_FMT_GRAY12LE"        "Y        , 12bpp, little-endian")
   (gray10be            "AV_PIX_FMT_GRAY10BE"        "Y        , 10bpp, big-endian")
   (gray10le            "AV_PIX_FMT_GRAY10LE"        "Y        , 10bpp, little-endian")
   (p016le              "AV_PIX_FMT_P016LE"          "like NV12, with 16bpp per component, little-endian")
   (p016be              "AV_PIX_FMT_P016BE"          "like NV12, with 16bpp per component, big-endian")
   (d3d11               "AV_PIX_FMT_D3D11"           "Hardware surfaces for Direct3D11")
   (gray9be             "AV_PIX_FMT_GRAY9BE"         "Y        , 9bpp, big-endian")
   (gray9le             "AV_PIX_FMT_GRAY9LE"         "Y        , 9bpp, little-endian")
   (gbrpf32be           "AV_PIX_FMT_GBRPF32BE"       "IEEE-754 single precision planar GBR 4:4:4,     96bpp, big-endian")
   (gbrpf32le           "AV_PIX_FMT_GBRPF32LE"       "IEEE-754 single precision planar GBR 4:4:4,     96bpp, little-endian")
   (gbrapf32be          "AV_PIX_FMT_GBRAPF32BE"      "IEEE-754 single precision planar GBRA 4:4:4:4, 128bpp, big-endian")
   (gbrapf32le          "AV_PIX_FMT_GBRAPF32LE"      "IEEE-754 single precision planar GBRA 4:4:4:4, 128bpp, little-endian")
   (drm-prime           "AV_PIX_FMT_DRM_PRIME"       "DRM-managed buffers exposed through PRIME buffer sharing. data[0] points to an AVDRMFrameDescriptor.")))
